# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIaTV2V6eMMQshU_9T20USn-7LGo4XG3
"""

import pandas as pd
import numpy as np

df = pd.read_csv("data/sales_data_sample.csv", encoding="latin1")
print(df.shape)
print(df.head())

print("\nMissing values:")
print(df.isnull().sum())

df = df.drop(columns=["ADDRESSLINE2", "STATE", "TERRITORY", "POSTALCODE"])
print("\nAfter dropping columns:", df.shape)

df["CITY"] = df["CITY"].fillna("Unknown")
print("Missing values after fix:")
print(df.isnull().sum())

before = len(df)
df = df.drop_duplicates()
after = len(df)
print(f"\nDuplicates removed: {before - after}")
print("Shape after dedup:", df.shape)

df["ORDERDATE"] = pd.to_datetime(df["ORDERDATE"])
print("\nORDERDATE dtype:", df["ORDERDATE"].dtype)
print(df["ORDERDATE"].head())

print("\nTop 5 countries by total sales:")
print(df.groupby("COUNTRY")["SALES"].sum().sort_values(ascending=False).head())

print("\nDeal size distribution:")
print(df["DEALSIZE"].value_counts())

print("\nOrder status breakdown:")
print(df["STATUS"].value_counts())

df.to_csv("sales_data_cleaned.csv", index=False)
print("\nSaved: sales_data_cleaned.csv")
print("Final shape:", df.shape)

